site_name: Hello Robot Documentation
site_url: https://docs.hello-robot.com
site_description: "Hello Robot User Documentation"
copyright: 'Copyright &copy; 2022 Hello Robot Inc'
site_author: Hello Robot Inc
use_directory_urls: True

theme:
 name: material
 features:
   - navigation.instant
 font: Arial
 palette:
  - scheme: default
    primary: hello-robot-light
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  - scheme: slate
    primary: hello-robot-dark
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
 logo: images/hello_robot_logo_light.png
 favicon: images/hello_robot_favicon.png
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - admonition



extra_css:
  - extra.css
plugins:
  - monorepo
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
      # uses the version specified via `mike deploy`
  - search
  - tags
#  - simple:
#      merge_docs_dir: true
#      include_extensions: [".css", ".png"]
#      ignore_folders:
#        - "repos/stretch_firmware/arduino"
#        - "repos/stretch_factory/updates"
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_root_heading: true
            show_source: false
            members_order: source
            heading_level: 3
            show_if_no_docstring: true
edit_uri: ''
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/twitter
    - icon: material/home
      link: https://hello-robot.com
    - icon: material/twitter
      link: https://twitter.com/HelloRobotInc
    - icon: material/github
      link: https://github.com/hello-robot
    - icon: material/linkedin
      link: https://linkedin.com/company/hello-robot-inc

nav:
  - Home: README.md
  - Primary:
    - Stretch Body: '!include ./repos/stretch_body/mkdocs.yml'
    - Stretch ROS: '!include ./repos/stretch_ros/mkdocs.yml'
  - Supporting:
    - Stretch Factory: '!include ./repos/stretch_factory/mkdocs.yml'
    - Stretch Firmware: '!include ./repos/stretch_firmware/mkdocs.yml'
  - Resources:
    - Stretch Forum: "https://forum.hello-robot.com/"
    - Stretch GitHub: "https://github.com/hello-robot"
    - Stretch Videos: "https://youtube.com/c/HelloRobot"