site_name: Stretch Docs
site_url: https://docs.hello-robot.com
site_description: "Hello Robot User Documentation"
copyright: 'Copyright &copy; 2020-2025 Hello Robot Inc'
site_author: Hello Robot Inc
use_directory_urls: True
edit_uri: ''

theme:
 name: material
 custom_dir: docs/overrides
 logo: images/hello_robot_logo_light.png
 favicon: images/hello_robot_favicon.png
 font:
   text: Roboto
   code: Roboto Mono
 palette:
  - scheme: default
    primary: hello-robot-light
 features:
   - navigation.footer

extra_css:
  - extra.css

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Anchor link
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition
  - footnotes

plugins:
  - search
  - monorepo
  - glightbox:
      skip_classes:
        - glightbox-skip
  - include-markdown

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: material/home
      link: https://hello-robot.com
    - icon: material/twitter
      link: https://twitter.com/HelloRobotInc
    - icon: material/github
      link: https://github.com/hello-robot
    - icon: material/linkedin
      link: https://linkedin.com/company/hello-robot-inc

nav:
  - Home: README.md
  - Getting Started:
    - Hello Robot!: getting_started/hello_robot.md
    - Connecting to Stretch: getting_started/connecting_to_stretch.md
    - Robot Overview: getting_started/stretch_hardware_overview.md
    - Writing Code: getting_started/writing_code.md
    - Demo 1 - Mapping & Navigation: getting_started/demos_mapping_and_navigation.md
    - Demo 2 - Web Teleop: getting_started/demos_web_teleop.md
    # - Demo 3 - Dexterous Teleop: getting_started/demos_dexterous_teleop.md # TODO
    - Community Resources: getting_started/community_resources.md
    - Getting help: getting_started/getting_help.md
  - Hardware Guides: '!include ./repos/stretch_hardware_guides/mkdocs.yml'
  - Software Overview:
    # - Software Architecture: software/architecture.md # TODO
    - Distributions: software/distributions.md
    - Updating Software: software/updating_software.md
    - Changelogs: software/changelogs.md
    # - Contributing: software/contributing.md # TODO
    - Installation Tutorials: '!include ./repos/stretch_install/mkdocs.yml'
  - Developing with Stretch: '!include ./repos/stretch_tutorials/mkdocs_dws.yml'
  - Python Tutorials: '!include ./repos/stretch_tutorials/mkdocs_pt.yml'
  - ROS 2 Tutorials: '!include ./repos/stretch_tutorials/mkdocs_rt.yml'
  - Extending Stretch:
    - Changing Tools: extending_stretch/changing_tools.md
    - URDF Management: extending_stretch/urdf_management.md
    - Extending Stretch with Additional Hardware: extending_stretch/extending_stretch_additional_hardware.md
  - Software Documentation: '!include ./repos/stretch_body/mkdocs.yml'
