[project]
name = "hello-robot-github-io"
version = "0.1.0"
description = "This repository generates the documentation hosted at [docs.hello-robot.com](https://docs.hello-robot.com)."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jinja2==3.0.3",
    "mike>=2.1.3",
    "mkdocs>=1.6.1",
    "mkdocs-glightbox>=0.5.2",
    "mkdocs-include-markdown-plugin>=7.2.0",
    "mkdocs-jupyter>=0.25.1",
    "mkdocs-material==9.6.9",
    "mkdocs-monorepo-plugin>=1.1.2",
    "mkdocs-redirects>=1.2.2",
    "mkdocs-same-dir>=0.1.3",
    "mkdocs-simple-plugin>=3.2.4",
    "mkdocstrings-python-legacy>=0.2.7",
    "pygments>=2.19.2",
    "pytkdocs[numpy-style]>=0.16.5",
]
