amcl:
  ros__parameters:
    base_frame_id: "base_link"
    global_frame_id: "map"
    set_initial_pose: false
    laser_likelihood_max_dist: 2.0
    laser_max_range: -1.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    resample_interval: 2
    robot_model_type: "differential"
    save_pose_rate: 0.5
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    use_map_topic: true
    scan_topic: "/scan"
    map_topic: "/map"
