global_costmap:
  plugins:
  - {name: static_map, type: "costmap_2d::StaticLayer"}
  - {name: 2d_obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 0.5
  static_map:
    map_topic: /map
