stretch_head_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint_head_pan
    - joint_head_tilt
  allow_partial_joints_goal: true

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_head_pan: {trajectory: 0.1, goal: 0.1}
    joint_head_tilt: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10