obstacle_range: 2.5
raytrace_range: 3.0

# robot_radius: 0.55
#             FL            BL              BR              FR
footprint: [[0.05,0.175],[-0.30,0.175],[-0.30,-0.175],[0.05,-0.175]]

footprint_padding: 0.0

transform_tolerance: 0.5
map_type: voxel

3d_obstacles:
  enabled: true
  max_obstacle_height:  1.5
  origin_z: 0.0
  z_resolution: 0.05
  z_voxels: 30
  unknown_threshold: 15
  mark_threshold: 0
  combination_method: 1
  track_unknown_space: true
  footprint_clearing_enabled: true
  publish_voxel_map: true
  observation_sources: cloud
  cloud:
    data_type: PointCloud2
    topic: /camera/depth/color/points
    sensor_frame: base_link
    marking: true
    clearing: true
    min_obstacle_height: 0.05


2d_obstacles:
  enabled: true
  observation_sources: laser
  laser:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    expected_update_rate: 0.3
    track_unknown_space: true


inflation_layer:
  enabled: true
  inflation_radius: 0.3
  cost_scaling_factor: 2.5
