obstacle_range: 2.5
raytrace_range: 2.5

robot_radius: 0.50

footprint_padding: 0.0

transform_tolerance: 0.5
map_type: costmap

3d_obstacles:
  enabled: true
  voxel_decay: 15     #seconds if linear, e^n if exponential
  decay_model: 0      #0=linear, 1=exponential, -1=persistent
  voxel_size: 0.05   #meters
  track_unknown_space: true   #default space is unknown
  observation_persistence: 0.0  #seconds
  unknown_threshold: 15     #voxel height
  mark_threshold: 0      #voxel height
  update_footprint_enabled: true
  combination_method: 1      #1=max, 0=override

  origin_z: 0.0    #meters
  publish_voxel_map: true   # default off
  transform_tolerance: 0.4
  mapping_mode: false  # default off, saves map not for navigation
  map_save_duration: 60     #default 60s, how often to autosave
  observation_sources: positive_obstacle negative_obstacle
  positive_obstacle:
    enabled: true                #default true, can be toggled on/off with associated service call
    data_type: PointCloud2
    topic: /camera/depth/color/points
    marking: true
    clearing: true
    min_obstacle_height: 0.05                  #default 0, meters
    #robot config defines max height here
    min_z: -0.1
    max_z: 6
    vertical_fov_angle: 0.7      #default 0.7, radians
    horizontal_fov_angle: 1.04   #default 1.04, radians
    decay_acceleration: 1       #default 0, 1/s^2. If laser scanner MUST be 0
    model_type: 0                #default 0 (depth camera). Use 1 for 3D Lidar

  negative_obstacle:
    enabled: true                #default true, can be toggled on/off with associated service call
    data_type: PointCloud2
    topic: /camera/depth/color/points
    marking: true
    clearing: false
    min_obstacle_height: -5                   #default 0, meters
    max_obstacle_height: -0.2
    min_z: -6
    max_z: 0.1
    vertical_fov_angle: 0.785398      #default 0.7, radians
    horizontal_fov_angle: 0.942478   #default 1.04, radians
    decay_acceleration: 1       #default 0, 1/s^2. If laser scanner MUST be 0
    model_type: 0                #default 0 (depth camera). Use 1 for 3D Lidar


2d_obstacles:
  observation_sources: laser
  laser: {data_type: LaserScan,
          topic: /scan,
          marking: true,
          clearing: true,
          expected_update_rate: 0.3,
          track_unknown_space: true
          }


inflation_layer:
  inflation_radius: 0.75
  cost_scaling_factor: 2.5
